#!/bin/sh

rsync -a --delete --exclude ".git" "/home/trevor/Documents/Github/mathnotes/output/html/" "/home/trevor/Documents/Github/github.io"

pushd "/home/trevor/Documents/Github/github.io"
git add .
git commit -m "$(date)"
git push
popd
